-- MySQL Script generated by MySQL Workbench
-- 03/17/16 09:41:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema watercleaner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema watercleaner
-- -----------------------------------------------------
USE `watercleaner` ;

-- -----------------------------------------------------
-- Table `watercleaner`.`commodity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watercleaner`.`commodity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commodityName` VARCHAR(100) NOT NULL,
  `commodityPrice` VARCHAR(100) NOT NULL,
  `commodityStock` VARCHAR(100) NOT NULL,
  `commodityImg` VARCHAR(1000) NOT NULL,
  `commoditySold` VARCHAR(100) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `watercleaner`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watercleaner`.`purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchaseChannel` VARCHAR(100) NOT NULL,
  `purchaseCreateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `purchaseFinishDate` DATETIME NULL,
  `purchasePrice` VARCHAR(100) NOT NULL,
  `purchaseStatus` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `watercleaner`.`defray`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watercleaner`.`defray` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchaseId` INT DEFAULT NULL,
  `commodityId` INT DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT 
    FOREIGN KEY (`purchaseId`)
    REFERENCES `watercleaner`.`purchase` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT 
    FOREIGN KEY (`commodityId`)
    REFERENCES `watercleaner`.`commodity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
